Add GPU selection to installer
Comfy-Org/desktop pull request #468
Opened 2024-12-12 13:22 UTC by webfiltered

### GPU installation options

- Adds GPU selection screen
- If a supported GPU is detected, it is pre-selected
- Allows user to pick whatever they wish
- Installs the appropriate `pytorch` for the selection
- Includes support for CPU mode
- Adds flag that auto-starts in CPU mode
- Stores selected GPU in config.json for future ref / debugging

2024-12-12 20:54 UTC, huchenlei requested changes

2024-12-12 20:54 UTC, huchenlei commented on src/utils.ts
> +    if (DesktopConfig.devCpuMode) return { isValid: true, gpu: 'cpu' };
Let's change the gpu wording in the PR to `device` instead as the value can be `cpu` as well.

2024-12-13 19:37 UTC, robinjhuang approved these changes

2024-12-13 19:37 UTC, robinjhuang commented on src/virtualEnvironment.ts
> +    const { selectedGpu } = this;
Feel like just using `this.selectedGpu` would be more readable here.

2024-12-13 19:37 UTC, robinjhuang commented on src/store/desktopConfig.ts
> +    return DesktopConfig.store.get('devCpuMode') === true;
Would it make sense to `devCpuMode` a constant?

2024-12-13 22:36 UTC, huchenlei requested changes

2024-12-13 22:36 UTC, huchenlei commented on src/preload.ts
> +    setCpuMode: async (enabled: boolean): Promise<void> => {
Where is this `setCpuMode` function get called? I cannot find its usage in the frontend PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1888/files

2024-12-13 22:36 UTC, huchenlei commented on src/preload.ts
> +    getGpu: async (): Promise<TorchDeviceType | undefined> => {
Let's rename this to`getDevice`.

2024-12-13 22:36 UTC, huchenlei commented on src/store/index.ts
> +  devCpuMode?: boolean;
Do we really need this flag? Can we compute this from `selectedDevice`? Or is there a difference between user cpu mode and dev cpu mode?

2024-12-13 22:36 UTC, huchenlei commented on src/utils.ts
> +  gpu?: TorchDeviceType;
Rename `gpu` to `device`.

2024-12-13 22:36 UTC, huchenlei commented on src/store/index.ts
> +  devCpuMode?: boolean;
If we need to pass extra arg to ComfyUI main.py, we can always set `launchArgs` in the user settings json.

2024-12-14 02:43 UTC, webfiltered commented on src/store/desktopConfig.ts
> +    return DesktopConfig.store.get('devCpuMode') === true;
Edit: Removed this setting entirely, as it is now redundant.

2024-12-14 02:56 UTC, webfiltered commented on src/store/index.ts
> +  devCpuMode?: boolean;
Possibly not.  This was leftover from the original design.

The reason I left it in was as a debugging option / explicit override, that you could configure from `config.json` in a text editor.  We could guide users having difficulty to do that in a simple troubleshooting doc.

2024-12-14 03:16 UTC, webfiltered commented on src/utils.ts
> +  gpu?: TorchDeviceType;
I left that one on purpose, as this is about hardware detection, not torch device.  It can't actually detect CPU mode.

TL;DR for below is: I made it logical by just removing the CPU part from `validateHardware` - it now does what it says on the box.

The logic to bypass the not supported screen was implemented when that screen could not be skipped.  Now that it can, showing the user this screen is beneficial to their understanding and the consequences of their selections.

I think even in explicit CPU mode, hardware validation should run & be recorded during installation.  Also, it is just simpler - less possible app states, less branches.

2024-12-14 08:18 UTC, webfiltered commented on src/preload.ts
> +    setCpuMode: async (enabled: boolean): Promise<void> => {
Removed.  Missed this when reordering commits.

2024-12-14 08:21 UTC, webfiltered commented on src/store/index.ts
> +  devCpuMode?: boolean;
Reviewed and removed.  No longer relevant after other changes.

2024-12-14 08:22 UTC, webfiltered commented on src/preload.ts
> +    getGpu: async (): Promise<TorchDeviceType | undefined> => {
Renamed this a second time to getDetectedGpu - what it actually does, now that the CPU bypass has been removed.

2024-12-14 08:22 UTC, webfiltered commented on src/virtualEnvironment.ts
> +    const { selectedGpu } = this;
Flagged for follow-up later on dereferencing in general.

2024-12-14 09:14 UTC, merged